/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 * 
 * This file provides type-safe resolution for string-based tokens.
 */
import type { IUserService } from './user/IUserService';
import type { IUserRepository } from './user/IUserRepository';
import type { ITodoService } from './todo/ITodoService';
import type { ITodoRepository } from './todo/ITodoRepository';

export interface ContainerRegistry {
  'IUserService': IUserService;
  'IUserRepository': IUserRepository;
  'ITodoService': ITodoService;
  'ITodoRepository': ITodoRepository;
}

type t = keyof ContainerRegistry
type value = ContainerRegistry[t]