/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 */
import { Container } from '@notjustcoders/di-container';
import type { ContainerRegistry } from './container.gen.d';
import { todoModule } from './modules/todoModule.module';
import { userModule } from './modules/userModule.module';

export const container = new Container<ContainerRegistry>();

container.registerModule(todoModule);
container.registerModule(userModule);
