/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 * 
 * This file provides type-safe resolution for string-based tokens.
 */
import type { ITodoService } from './todo/ITodoService';
import type { ITodoRepository } from './todo/ITodoRepository';
import type { IUserService } from './user/IUserService';
import type { IUserRepository } from './user/IUserRepository';
import type { Todo } from './todo/Todo';
import type { User } from './user/User';

export interface ContainerRegistry {
  'ITodoService': ITodoService;
  'ITodoRepository': ITodoRepository;
  'IUserService': IUserService;
  'IUserRepository': IUserRepository;
  'Todo': Todo;
  'User': User;
}
