/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 */
import { Container } from 'ioc-arise';
import type { ContainerRegistry } from './container.gen.d';
import { moduleB } from './modules/moduleB.module';
import { moduleA } from './modules/moduleA.module';

export const container = new Container<ContainerRegistry>();

container.registerModule(moduleB);
container.registerModule(moduleA);
