/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 * 
 * This file provides type-safe resolution for string-based tokens.
 */
import type { IServiceB } from './interfaces/IServiceB';
import type { IServiceA } from './interfaces/IServiceA';

export interface ContainerRegistry {
  'IServiceB': IServiceB;
  'IServiceA': IServiceA;
}
