/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 * 
 * This file provides type-safe resolution for string-based tokens.
 */
import type { IUpdateTodoInputPort } from './ports/ITodoInputPort';
import type { IGetUserInputPort } from './ports/IInputPort';
import type { IGetTodosByUserInputPort } from './ports/ITodoInputPort';
import type { IGetTodoInputPort } from './ports/ITodoInputPort';
import type { IDeleteUserInputPort } from './ports/IInputPort';
import type { IDeleteTodoInputPort } from './ports/ITodoInputPort';
import type { ICreateUserInputPort } from './ports/IInputPort';
import type { ICreateTodoInputPort } from './ports/ITodoInputPort';
import type { IUserRepository } from './repositories/IUserRepository';
import type { ITodoRepository } from './repositories/ITodoRepository';
import type { IUpdateTodoOutputPort } from './ports/ITodoOutputPort';
import type { IGetUserOutputPort } from './ports/IOutputPort';
import type { IGetTodosByUserOutputPort } from './ports/ITodoOutputPort';
import type { IGetTodoOutputPort } from './ports/ITodoOutputPort';
import type { IDeleteUserOutputPort } from './ports/IOutputPort';
import type { IDeleteTodoOutputPort } from './ports/ITodoOutputPort';
import type { ICreateUserOutputPort } from './ports/IOutputPort';
import type { ICreateTodoOutputPort } from './ports/ITodoOutputPort';

export interface ContainerRegistry {
  'IUpdateTodoInputPort': IUpdateTodoInputPort;
  'IGetUserInputPort': IGetUserInputPort;
  'IGetTodosByUserInputPort': IGetTodosByUserInputPort;
  'IGetTodoInputPort': IGetTodoInputPort;
  'IDeleteUserInputPort': IDeleteUserInputPort;
  'IDeleteTodoInputPort': IDeleteTodoInputPort;
  'ICreateUserInputPort': ICreateUserInputPort;
  'ICreateTodoInputPort': ICreateTodoInputPort;
  'IUserRepository': IUserRepository;
  'ITodoRepository': ITodoRepository;
  'IUpdateTodoOutputPort': IUpdateTodoOutputPort;
  'IGetUserOutputPort': IGetUserOutputPort;
  'IGetTodosByUserOutputPort': IGetTodosByUserOutputPort;
  'IGetTodoOutputPort': IGetTodoOutputPort;
  'IDeleteUserOutputPort': IDeleteUserOutputPort;
  'IDeleteTodoOutputPort': IDeleteTodoOutputPort;
  'ICreateUserOutputPort': ICreateUserOutputPort;
  'ICreateTodoOutputPort': ICreateTodoOutputPort;
}
