/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 * 
 * Module: ModuleA
 */
import { ContainerModule, Lifecycle } from 'ioc-arise';
import { ServiceA } from '../services/ServiceA';

export const moduleA = new ContainerModule()
  .register('IServiceA', { useClass: ServiceA, dependencies: ['IServiceB'], lifecycle: Lifecycle.Singleton });
