/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 * 
 * This file provides type-safe resolution for string-based tokens.
 */
import { createPermanentlyDeleteWordUseCase } from './application/vocabulary/PermanentlyDeleteWordUseCase';

export interface ContainerRegistry {
  'createPermanentlyDeleteWordUseCase': ReturnType<typeof createPermanentlyDeleteWordUseCase>;
}
