/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 */
import { Container, Lifecycle } from 'ioc-arise';
import type { ContainerRegistry } from './container.gen.d';
import { ClassB } from './services/ClassB';
import { ClassA } from './services/ClassA';

export const container = new Container<ContainerRegistry>();

container.register('IClassB', {
  useClass: ClassB,
  dependencies: ['IClassA'],
  lifecycle: Lifecycle.Singleton,
});

container.register('IClassA', {
  useClass: ClassA,
  dependencies: ['IClassB'],
  lifecycle: Lifecycle.Singleton,
});
