/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 * 
 * This file provides type-safe resolution for string-based tokens.
 */
import type { IClassB } from './interfaces/IClassB';
import type { IClassA } from './interfaces/IClassA';

export interface ContainerRegistry {
  'IClassB': IClassB;
  'IClassA': IClassA;
}
