/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 *
 * Module: InfraModule
 */
import { ContainerModule, Lifecycle } from '@notjustcoders/di-container';
import { createLogger } from '../src/infra/logger/LoggerFactory';
import { appConfig } from '../src/infra/config/appConfig';

export const infraModule = new ContainerModule()
  .register('ILogger', { useFactory: createLogger, dependencies: ['AppConfig'], lifecycle: Lifecycle.Transient })
  .register('AppConfig', { useValue: appConfig, lifecycle: Lifecycle.Singleton });
