/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 *
 * Module: NotificationModule
 */
import { ContainerModule, Lifecycle } from '@notjustcoders/di-container';
import { GetStatisticsUseCase } from '../src/application/notifications/GetStatisticsUseCase';
import { WordStatisticsService } from '../src/application/stats/WordStatisticsService';

export const notificationModule = new ContainerModule()
  .register(GetStatisticsUseCase, { useClass: GetStatisticsUseCase, dependencies: [WordStatisticsService, 'ILogger', 'AppConfig'], lifecycle: Lifecycle.Singleton });
