/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 *
 * Module: SharedModule
 */
import { ContainerModule, Lifecycle } from '@notjustcoders/di-container';
import { ConsoleLogger, createLogger } from '../src/shared/logger';
import { appConfig } from '../src/shared/config';

export const sharedModule = new ContainerModule()
  .register(ConsoleLogger, { useClass: ConsoleLogger, lifecycle: Lifecycle.Singleton })
  .register('ILogger', { useFactory: createLogger, lifecycle: Lifecycle.Transient })
  .register('AppConfig', { useValue: appConfig, lifecycle: Lifecycle.Singleton });
