/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 *
 * Module: StatsModule
 */
import { ContainerModule, Lifecycle } from '@notjustcoders/di-container';
import { WordStatisticsService } from '../src/application/stats/WordStatisticsService';

export const statsModule = new ContainerModule()
  .register(WordStatisticsService, { useClass: WordStatisticsService, lifecycle: Lifecycle.Singleton });
