/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 * 
 * Module: ModuleB
 */
import { ContainerModule, Lifecycle } from 'ioc-arise';
import { ServiceB } from '../services/ServiceB';

export const moduleB = new ContainerModule()
  .register('IServiceB', { useClass: ServiceB, dependencies: ['IServiceA'], lifecycle: Lifecycle.Singleton });
