/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 *
 * Module: TodoModule
 */
import { ContainerModule, Lifecycle } from '@notjustcoders/di-container';
import { TodoRepository } from '../todo/TodoRepository';
import { createAddTodoUseCase } from '../todo/factories/createAddTodoUseCase';

export const todoModule = new ContainerModule()
  .register('ITodoRepository', { useClass: TodoRepository, lifecycle: Lifecycle.Singleton })
  .register('createAddTodoUseCase', { useFactory: (userRepo, todoRepo) => createAddTodoUseCase({ userRepo, todoRepo }), dependencies: ['IUserRepository', 'ITodoRepository'], lifecycle: Lifecycle.Singleton });
