/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 *
 * Module: UserModule
 */
import { ContainerModule, Lifecycle } from '@notjustcoders/di-container';
import { UserRepository } from '../user/UserRepository';
import { createFindUserUseCase } from '../user/factories/createFindUserUseCase';

export const userModule = new ContainerModule()
  .register('IUserRepository', { useClass: UserRepository, lifecycle: Lifecycle.Singleton })
  .register('createFindUserUseCase', { useFactory: createFindUserUseCase, dependencies: ['IUserRepository'], lifecycle: Lifecycle.Singleton });
