/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 */
import { Container, Lifecycle } from '@notjustcoders/di-container';
import type { ContainerRegistry } from './container.gen.d';
import { UserService } from './services/UserService';
import { createUserRepository } from './repositories/createUserRepository';
import { appConfig } from './config/appConfig';

export const container = new Container<ContainerRegistry>();

container.register('IUserService', {
  useClass: UserService,
  dependencies: ['IUserRepository'],
  lifecycle: Lifecycle.Singleton,
});

container.register('IUserRepository', {
  useFactory: (config) => createUserRepository({ config }),
  dependencies: ['IAppConfig'],
  lifecycle: Lifecycle.Transient,
});

container.register('IAppConfig', {
  useValue: appConfig,
  lifecycle: Lifecycle.Singleton,
});
