/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 * 
 * This file provides type-safe resolution for string-based tokens.
 */
import type { IUserService } from './services/IUserService';
import type { IUserRepository } from './repositories/IUserRepository';
import type { IAppConfig } from './config/IAppConfig';

export interface ContainerRegistry {
  'IUserService': IUserService;
  'IUserRepository': IUserRepository;
  'IAppConfig': IAppConfig;
}
