/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 */
import { Container, Lifecycle } from '@notjustcoders/di-container';
import type { ContainerRegistry } from './container.gen.d';
import { ProductService } from './services/ProductService';
import { createProductRepository } from './repositories/createProductRepository';
import { consoleLogger } from './logger/consoleLogger';
import { appConfig } from './config/appConfig';

export const container = new Container<ContainerRegistry>();

container.register('IProductService', {
  useClass: ProductService,
  dependencies: ['IProductRepository'],
  lifecycle: Lifecycle.Singleton,
});

container.register('IProductRepository', {
  useFactory: createProductRepository,
  dependencies: ['IAppConfig', 'ILogger'],
  lifecycle: Lifecycle.Transient,
});

container.register('ILogger', {
  useValue: consoleLogger,
  lifecycle: Lifecycle.Singleton,
});

container.register('IAppConfig', {
  useValue: appConfig,
  lifecycle: Lifecycle.Singleton,
});
