/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 * 
 * This file provides type-safe resolution for string-based tokens.
 */
import type { IProductService } from './services/IProductService';
import type { IProductRepository } from './repositories/IProductRepository';
import type { ILogger } from './logger/ILogger';
import type { IAppConfig } from './config/IAppConfig';

export interface ContainerRegistry {
  'IProductService': IProductService;
  'IProductRepository': IProductRepository;
  'ILogger': ILogger;
  'IAppConfig': IAppConfig;
}
