/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 *
 * Module: CoreModule
 */
import { ContainerModule, Lifecycle } from '@notjustcoders/di-container';
import { UserService } from '../user/UserService';
import { ProductService } from '../product/ProductService';

export const coreModule = new ContainerModule()
  .register('IUserService', { useClass: UserService, dependencies: [IUserRepository, ICache], lifecycle: Lifecycle.Singleton })
  .register('IProductService', { useClass: ProductService, dependencies: [IProductRepository, 'IUserService'], lifecycle: Lifecycle.Singleton });
