/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 */
import { Container, Lifecycle } from '@notjustcoders/di-container';
import type { ContainerRegistry } from './container.gen.d';
import { TransientService } from './services/TransientService';
import { SingletonService } from './services/SingletonService';
import { MixedService } from './services/MixedService';

export const container = new Container<ContainerRegistry>();

container.register('ITransientService', {
  useClass: TransientService,
  lifecycle: Lifecycle.Transient,
});

container.register('ISingletonService', {
  useClass: SingletonService,
  lifecycle: Lifecycle.Singleton,
});

container.register(MixedService, {
  useClass: MixedService,
  dependencies: ['ISingletonService', 'ITransientService'],
  lifecycle: Lifecycle.Singleton,
});
