/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 * 
 * This file provides type-safe resolution for string-based tokens.
 */
import type { ITransientService } from './services/ITransientService';
import type { ISingletonService } from './services/ISingletonService';
import type { MixedService } from './services/MixedService';

export interface ContainerRegistry {
  'ITransientService': ITransientService;
  'ISingletonService': ISingletonService;
  'MixedService': MixedService;
}
