/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 *
 * Module: ProductModule
 */
import { ContainerModule, Lifecycle } from '@notjustcoders/di-container';
import { ProductService } from '../product/ProductService';
import { createProductRepository } from '../product/createProductRepository';

export const productModule = new ContainerModule()
  .register('IProductService', { useClass: ProductService, dependencies: ['IProductRepository', 'IUserService'], lifecycle: Lifecycle.Singleton })
  .register('IProductRepository', { useFactory: (config, logger) => createProductRepository({ config, logger }), dependencies: ['IAppConfig', 'ILogger'], lifecycle: Lifecycle.Singleton });
