/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 * 
 * This file provides type-safe resolution for string-based tokens.
 */
import type { UserRepository } from './implementations/UserRepository';
import type { ProductRepository } from './implementations/ProductRepository';
import type { UserUseCase } from './use-cases/UserUseCase';
import type { ProductUseCase } from './use-cases/ProductUseCase';
import type { InternalProductNestedUseCase } from './use-cases/InternalProductNestedUseCase';
import { createUserModuleContainer } from './UserModule.gen';
import { createProductModuleContainer } from './ProductModule.gen';

export interface ContainerRegistry {
  'AbstractUserRepository': UserRepository;
  'AbstractProductRepository': ProductRepository;
  'UserUseCase': UserUseCase;
  'ProductUseCase': ProductUseCase;
  'InternalProductNestedUseCase': InternalProductNestedUseCase;
  'createUserModuleContainer': ReturnType<typeof createUserModuleContainer>;
  'createProductModuleContainer': ReturnType<typeof createProductModuleContainer>;
}
