/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 * 
 * This file provides type-safe resolution for string-based tokens.
 */
import type { UserRepository } from './implementations/UserRepository';
import type { ProductRepository } from './implementations/ProductRepository';

export interface ContainerRegistry {
  'AbstractUserRepository': UserRepository;
  'AbstractProductRepository': ProductRepository;
}
