/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 *
 * Module: UserModule
 */
import { ContainerModule, Lifecycle } from '@notjustcoders/di-container';
import { UserService } from '../../user/UserService';
import { createUserRepository } from '../../user/createUserRepository';

export const userModule = new ContainerModule()
  .register('IUserService', { useClass: UserService, dependencies: ['IUserRepository', 'ICache'], lifecycle: Lifecycle.Singleton })
  .register('IUserRepository', { useFactory: createUserRepository, dependencies: ['IAppConfig', 'ILogger'], lifecycle: Lifecycle.Transient });
