/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 */
import { Container, Lifecycle } from '@notjustcoders/di-container';
import type { ContainerRegistry } from './container.gen.d';
import { UserController } from './use-cases/UserController';
import { GetUserUseCase } from './use-cases/GetUserUseCase';
import { CreateUserUseCase } from './use-cases/CreateUserUseCase';
import { EmailService } from './services/EmailService';
import { ApplicationService } from './services/ApplicationService';
import { UserRepository } from './repositories/UserRepository';

export const container = new Container<ContainerRegistry>();

container.register(UserController, {
  useClass: UserController,
  dependencies: [CreateUserUseCase, GetUserUseCase],
  lifecycle: Lifecycle.Singleton,
});

container.register(GetUserUseCase, {
  useClass: GetUserUseCase,
  dependencies: ['IUserRepository'],
  lifecycle: Lifecycle.Singleton,
});

container.register(CreateUserUseCase, {
  useClass: CreateUserUseCase,
  dependencies: ['IUserRepository', 'IEmailService'],
  lifecycle: Lifecycle.Singleton,
});

container.register('IEmailService', {
  useClass: EmailService,
  lifecycle: Lifecycle.Singleton,
});

container.register('IApplicationService', {
  useClass: ApplicationService,
  dependencies: [UserController],
  lifecycle: Lifecycle.Singleton,
});

container.register('IUserRepository', {
  useClass: UserRepository,
  lifecycle: Lifecycle.Singleton,
});
