/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 * 
 * This file provides type-safe resolution for string-based tokens.
 */
import type { IEmailService } from './services/IEmailService';
import type { IApplicationService } from './services/IApplicationService';
import type { IUserRepository } from './repositories/IUserRepository';
import type { UserController } from './use-cases/UserController';
import type { GetUserUseCase } from './use-cases/GetUserUseCase';
import type { CreateUserUseCase } from './use-cases/CreateUserUseCase';

export interface ContainerRegistry {
  'IEmailService': IEmailService;
  'IApplicationService': IApplicationService;
  'IUserRepository': IUserRepository;
  'UserController': UserController;
  'GetUserUseCase': GetUserUseCase;
  'CreateUserUseCase': CreateUserUseCase;
}
