/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 * 
 * This file provides type-safe resolution for string-based tokens.
 */
import type { IUserRepository } from './repositories/IUserRepository';
import type { IEmailService } from './services/IEmailService';
import type { IApplicationService } from './services/IApplicationService';

export interface ContainerRegistry {
  'IUserRepository': IUserRepository;
  'IEmailService': IEmailService;
  'IApplicationService': IApplicationService;
}
