/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 */
import { Container } from '@notjustcoders/di-container';
import type { ContainerRegistry } from './container.gen.d';
import { userModule } from './modules/userModule.module';
import { productModule } from './modules/productModule.module';

export const container = new Container<ContainerRegistry>();

container.registerModule(userModule);
container.registerModule(productModule);
