/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 * 
 * Module: CoreModule
 */
import { ContainerModule, Lifecycle } from '@notjustcoders/di-container';
import { User } from '../entities/User';
import { Todo } from '../entities/Todo';

export const coreModule = new ContainerModule()
  .register(User, { useClass: User, lifecycle: Lifecycle.Singleton })
  .register(Todo, { useClass: Todo, lifecycle: Lifecycle.Singleton });
