/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 * 
 * Module: UserModule
 */
import { ContainerModule, Lifecycle } from 'ioc-arise';
import { GetUserUseCase } from '../use-cases/GetUserUseCase';
import { GetTodosByUserUseCase } from '../use-cases/GetTodosByUserUseCase';
import { DeleteUserUseCase } from '../use-cases/DeleteUserUseCase';
import { CreateUserUseCase } from '../use-cases/CreateUserUseCase';
import { UserRepository } from '../repositories/UserRepository';
import { GetUserPresenter } from '../presenters/GetUserPresenter';
import { GetTodosByUserPresenter } from '../presenters/GetTodosByUserPresenter';
import { DeleteUserPresenter } from '../presenters/DeleteUserPresenter';
import { CreateUserPresenter } from '../presenters/CreateUserPresenter';

export const userModule = new ContainerModule()
  .register('IGetUserInputPort', { useClass: GetUserUseCase, dependencies: ['IUserRepository', 'IGetUserOutputPort'], lifecycle: Lifecycle.Singleton })
  .register('IGetTodosByUserInputPort', { useClass: GetTodosByUserUseCase, dependencies: ['IUserRepository', 'IGetTodosByUserOutputPort'], lifecycle: Lifecycle.Singleton })
  .register('IDeleteUserInputPort', { useClass: DeleteUserUseCase, dependencies: ['IUserRepository', 'IDeleteUserOutputPort'], lifecycle: Lifecycle.Singleton })
  .register('ICreateUserInputPort', { useClass: CreateUserUseCase, dependencies: ['IUserRepository', 'ICreateUserOutputPort'], lifecycle: Lifecycle.Singleton })
  .register('IUserRepository', { useClass: UserRepository, lifecycle: Lifecycle.Singleton })
  .register('IGetUserOutputPort', { useClass: GetUserPresenter, lifecycle: Lifecycle.Transient })
  .register('IGetTodosByUserOutputPort', { useClass: GetTodosByUserPresenter, lifecycle: Lifecycle.Transient })
  .register('IDeleteUserOutputPort', { useClass: DeleteUserPresenter, lifecycle: Lifecycle.Transient })
  .register('ICreateUserOutputPort', { useClass: CreateUserPresenter, lifecycle: Lifecycle.Transient });
