/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 */
import { Container } from '@notjustcoders/di-container';
import type { ContainerRegistry } from './container.gen.d';
import { reviewModule } from './modules/reviewModule.module';
import { statisticsModule } from './modules/statisticsModule.module';
import { notificationModule } from './modules/notificationModule.module';
import { vocabularyModule } from './modules/vocabularyModule.module';
import { sharedModule } from './modules/sharedModule.module';

export const container = new Container<ContainerRegistry>();

container.registerModule(reviewModule);
container.registerModule(statisticsModule);
container.registerModule(notificationModule);
container.registerModule(vocabularyModule);
container.registerModule(sharedModule);
