/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 * 
 * This file provides type-safe resolution for string-based tokens.
 */
import type { GetStatisticsUseCase } from '../application/statistics/GetStatisticsUseCase';
import { createStartReviewSessionUseCase } from '../infra/services/ReviewServices';
import { createRecordAnswerUseCase } from '../infra/services/ReviewServices';
import { createEndReviewSessionUseCase } from '../infra/services/ReviewServices';
import { createOnReviewSessionEnded } from '../infra/services/ReviewServices';
import { createOnReviewSessionEndedDailyReminder } from '../application/notifications/NotificationEntities';
import { createAddWordUseCase } from '../infra/persistence/vocabulary/VocabularyFactories';
import { createGetWordUseCase } from '../infra/persistence/vocabulary/VocabularyFactories';
import { createSearchWordsUseCase } from '../infra/persistence/vocabulary/VocabularyFactories';
import { createUpdateWordUseCase } from '../infra/persistence/vocabulary/VocabularyFactories';
import { createGetAllWordsUseCase } from '../infra/persistence/vocabulary/VocabularyFactories';
import { createDeleteWordUseCase } from '../infra/persistence/vocabulary/VocabularyFactories';
import { createCreateSourceUseCase } from '../infra/persistence/vocabulary/VocabularyFactories';
import { createGetAllSourcesUseCase } from '../infra/persistence/vocabulary/VocabularyFactories';
import { createUpdateSourceUseCase } from '../infra/persistence/vocabulary/VocabularyFactories';
import { createDeleteSourceUseCase } from '../infra/persistence/vocabulary/VocabularyFactories';

export interface ContainerRegistry {
  'SpacedRepetitionService': SpacedRepetitionService;
  'ReviewSessionBuilderService': ReviewSessionBuilderService;
  'INotificationDecisionService': INotificationDecisionService;
  'INotificationContentBuilder': INotificationContentBuilder;
  'ILocalNotificationScheduler': ILocalNotificationScheduler;
  'IUserNotificationPreferencesRepository': IUserNotificationPreferencesRepository;
  'GetStatisticsUseCase': GetStatisticsUseCase;
  'IReviewSessionRepository': IReviewSessionRepository;
  'createStartReviewSessionUseCase': ReturnType<typeof createStartReviewSessionUseCase>;
  'createRecordAnswerUseCase': ReturnType<typeof createRecordAnswerUseCase>;
  'createEndReviewSessionUseCase': ReturnType<typeof createEndReviewSessionUseCase>;
  'createOnReviewSessionEnded': ReturnType<typeof createOnReviewSessionEnded>;
  'ScheduleDailyReviewReminderUseCase': ScheduleDailyReviewReminderUseCase;
  'createOnReviewSessionEndedDailyReminder': ReturnType<typeof createOnReviewSessionEndedDailyReminder>;
  'IWordEntryRepository': IWordEntryRepository;
  'ISourceRepository': ISourceRepository;
  'createAddWordUseCase': ReturnType<typeof createAddWordUseCase>;
  'createGetWordUseCase': ReturnType<typeof createGetWordUseCase>;
  'createSearchWordsUseCase': ReturnType<typeof createSearchWordsUseCase>;
  'createUpdateWordUseCase': ReturnType<typeof createUpdateWordUseCase>;
  'createGetAllWordsUseCase': ReturnType<typeof createGetAllWordsUseCase>;
  'createDeleteWordUseCase': ReturnType<typeof createDeleteWordUseCase>;
  'createCreateSourceUseCase': ReturnType<typeof createCreateSourceUseCase>;
  'createGetAllSourcesUseCase': ReturnType<typeof createGetAllSourcesUseCase>;
  'createUpdateSourceUseCase': ReturnType<typeof createUpdateSourceUseCase>;
  'createDeleteSourceUseCase': ReturnType<typeof createDeleteSourceUseCase>;
  'IEventBus': IEventBus;
  'IUuidGenerator': IUuidGenerator;
  'sm2StateStore': typeof sm2StateStore;
}
