/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 */
import { Container } from '@notjustcoders/di-container';
import type { ContainerRegistry } from './container.gen.d';
import { statsModule } from './modules/statsModule.module';
import { notificationModule } from './modules/notificationModule.module';
import { infraModule } from './modules/infraModule.module';

export const container = new Container<ContainerRegistry>();

container.registerModule(statsModule);
container.registerModule(notificationModule);
container.registerModule(infraModule);
