/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 * 
 * This file provides type-safe resolution for string-based tokens.
 */
import type { WordStatisticsService } from './src/application/stats/WordStatisticsService';
import type { GetStatisticsUseCase } from './src/application/notifications/GetStatisticsUseCase';
import type { ILogger } from './src/infra/config/appConfig';
import type { AppConfig } from './src/infra/config/AppConfig';

export interface ContainerRegistry {
  'WordStatisticsService': WordStatisticsService;
  'GetStatisticsUseCase': GetStatisticsUseCase;
  'ILogger': ILogger;
  'AppConfig': AppConfig;
}
