/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 * 
 * Module: UserModule
 */
import { ContainerModule, Lifecycle } from '@notjustcoders/di-container';
import { UserUseCase } from '../use-cases/UserUseCase';
import { UserRepository } from '../implementations/UserRepository';

export const userModule = new ContainerModule()
  .register(UserUseCase, { useClass: UserUseCase, dependencies: ['AbstractUserRepository'], lifecycle: Lifecycle.Singleton })
  .register('AbstractUserRepository', { useClass: UserRepository, lifecycle: Lifecycle.Singleton });
