/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 * 
 * This file provides type-safe resolution for string-based tokens.
 */
import type { IUserService } from './services/IUserService';
import type { IConfigService } from './services/IConfigService';

export interface ContainerRegistry {
  'IUserService': IUserService;
  'IConfigService': IConfigService;
}
