/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 */
import { Container, Lifecycle } from 'ioc-arise';
import type { ContainerRegistry } from './container.gen.d';
import { TodoService } from './services/TodoService';
import { InMemoryTodoRepository } from './repositories/InMemoryTodoRepository';
import { Todo } from './entities/Todo';

export const container = new Container<ContainerRegistry>();

container.register('ITodoService', {
  useClass: TodoService,
  dependencies: ['ITodoRepository'],
  lifecycle: Lifecycle.Singleton,
});

container.register('ITodoRepository', {
  useClass: InMemoryTodoRepository,
  lifecycle: Lifecycle.Singleton,
});

container.register(Todo, {
  useClass: Todo,
  lifecycle: Lifecycle.Singleton,
});
