/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 * 
 * This file provides type-safe resolution for string-based tokens.
 */
import type { ITodoService } from './services/ITodoService';
import type { ITodoRepository } from './repositories/ITodoRepository';

export interface ContainerRegistry {
  'ITodoService': ITodoService;
  'ITodoRepository': ITodoRepository;
}
