/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 * 
 * This file provides type-safe resolution for string-based tokens.
 */
import type { ITodoRepository } from './repositories/ITodoRepository';
import type { ITodoService } from './services/ITodoService';
import type { Todo } from './entities/Todo';

export interface ContainerRegistry {
  'ITodoRepository': ITodoRepository;
  'ITodoService': ITodoService;
  'Todo': Todo;
}
