/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 */
import { Container, Lifecycle } from '@notjustcoders/di-container';
import type { ContainerRegistry } from './container.gen.d';
import { UserService } from './services/UserService';
import { createInMemoryUserRepository } from './repositories/createInMemoryUserRepository';

export const container = new Container<ContainerRegistry>();

container.register('IUserService', {
  useClass: UserService,
  dependencies: ['IUserRepository'],
  lifecycle: Lifecycle.Singleton,
});

container.register('IUserRepository', {
  useFactory: createInMemoryUserRepository,
  lifecycle: Lifecycle.Transient,
});
