/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 */
import { Container, Lifecycle } from 'ioc-arise';
import type { ContainerRegistry } from './container.gen.d';
import { UserRepository } from './user/UserRepository';
import { UserController } from './user/UserController';
import { UpdateItemUseCase as UserUpdateItemUseCase } from './user/UpdateItemUseCase';
import { ListItemsUseCase as UserListItemsUseCase } from './user/ListItemsUseCase';
import { GetItemUseCase as UserGetItemUseCase } from './user/GetItemUseCase';
import { DeleteItemUseCase as UserDeleteItemUseCase } from './user/DeleteItemUseCase';
import { CreateItemUseCase as UserCreateItemUseCase } from './user/CreateItemUseCase';
import { UpdateItemUseCase as ProductUpdateItemUseCase } from './product/UpdateItemUseCase';
import { ProductRepository } from './product/ProductRepository';
import { ProductController } from './product/ProductController';
import { ListItemsUseCase as ProductListItemsUseCase } from './product/ListItemsUseCase';
import { GetItemUseCase as ProductGetItemUseCase } from './product/GetItemUseCase';
import { DeleteItemUseCase as ProductDeleteItemUseCase } from './product/DeleteItemUseCase';
import { CreateItemUseCase as ProductCreateItemUseCase } from './product/CreateItemUseCase';
import { UpdateItemUseCase as OrderUpdateItemUseCase } from './order/UpdateItemUseCase';
import { OrderRepository } from './order/OrderRepository';
import { OrderController } from './order/OrderController';
import { ListItemsUseCase as OrderListItemsUseCase } from './order/ListItemsUseCase';
import { GetItemUseCase as OrderGetItemUseCase } from './order/GetItemUseCase';
import { DeleteItemUseCase as OrderDeleteItemUseCase } from './order/DeleteItemUseCase';
import { CreateItemUseCase as OrderCreateItemUseCase } from './order/CreateItemUseCase';

export const container = new Container<ContainerRegistry>();

container.register('IUserRepository', {
  useClass: UserRepository,
  lifecycle: Lifecycle.Singleton,
});

container.register(UserController, {
  useClass: UserController,
  dependencies: [UserCreateItemUseCase, UserUpdateItemUseCase, UserDeleteItemUseCase, UserGetItemUseCase, UserListItemsUseCase],
  lifecycle: Lifecycle.Singleton,
});

container.register(UserUpdateItemUseCase, {
  useClass: UserUpdateItemUseCase,
  dependencies: ['IUserRepository'],
  lifecycle: Lifecycle.Singleton,
});

container.register(UserListItemsUseCase, {
  useClass: UserListItemsUseCase,
  dependencies: ['IUserRepository'],
  lifecycle: Lifecycle.Singleton,
});

container.register(UserGetItemUseCase, {
  useClass: UserGetItemUseCase,
  dependencies: ['IUserRepository'],
  lifecycle: Lifecycle.Singleton,
});

container.register(UserDeleteItemUseCase, {
  useClass: UserDeleteItemUseCase,
  dependencies: ['IUserRepository'],
  lifecycle: Lifecycle.Singleton,
});

container.register(UserCreateItemUseCase, {
  useClass: UserCreateItemUseCase,
  dependencies: ['IUserRepository'],
  lifecycle: Lifecycle.Singleton,
});

container.register(ProductUpdateItemUseCase, {
  useClass: ProductUpdateItemUseCase,
  dependencies: ['IProductRepository'],
  lifecycle: Lifecycle.Singleton,
});

container.register('IProductRepository', {
  useClass: ProductRepository,
  lifecycle: Lifecycle.Singleton,
});

container.register(ProductController, {
  useClass: ProductController,
  dependencies: [ProductCreateItemUseCase, ProductUpdateItemUseCase, ProductDeleteItemUseCase, ProductGetItemUseCase, ProductListItemsUseCase],
  lifecycle: Lifecycle.Singleton,
});

container.register(ProductListItemsUseCase, {
  useClass: ProductListItemsUseCase,
  dependencies: ['IProductRepository'],
  lifecycle: Lifecycle.Singleton,
});

container.register(ProductGetItemUseCase, {
  useClass: ProductGetItemUseCase,
  dependencies: ['IProductRepository'],
  lifecycle: Lifecycle.Singleton,
});

container.register(ProductDeleteItemUseCase, {
  useClass: ProductDeleteItemUseCase,
  dependencies: ['IProductRepository'],
  lifecycle: Lifecycle.Singleton,
});

container.register(ProductCreateItemUseCase, {
  useClass: ProductCreateItemUseCase,
  dependencies: ['IProductRepository'],
  lifecycle: Lifecycle.Singleton,
});

container.register(OrderUpdateItemUseCase, {
  useClass: OrderUpdateItemUseCase,
  dependencies: ['IOrderRepository'],
  lifecycle: Lifecycle.Singleton,
});

container.register('IOrderRepository', {
  useClass: OrderRepository,
  lifecycle: Lifecycle.Singleton,
});

container.register(OrderController, {
  useClass: OrderController,
  dependencies: [OrderCreateItemUseCase, OrderUpdateItemUseCase, OrderDeleteItemUseCase, OrderGetItemUseCase, OrderListItemsUseCase],
  lifecycle: Lifecycle.Singleton,
});

container.register(OrderListItemsUseCase, {
  useClass: OrderListItemsUseCase,
  dependencies: ['IOrderRepository'],
  lifecycle: Lifecycle.Singleton,
});

container.register(OrderGetItemUseCase, {
  useClass: OrderGetItemUseCase,
  dependencies: ['IOrderRepository'],
  lifecycle: Lifecycle.Singleton,
});

container.register(OrderDeleteItemUseCase, {
  useClass: OrderDeleteItemUseCase,
  dependencies: ['IOrderRepository'],
  lifecycle: Lifecycle.Singleton,
});

container.register(OrderCreateItemUseCase, {
  useClass: OrderCreateItemUseCase,
  dependencies: ['IOrderRepository'],
  lifecycle: Lifecycle.Singleton,
});
