/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 * 
 * This file provides type-safe resolution for string-based tokens.
 */
import type { IUserRepository } from './user/CreateItemUseCase';
import type { IProductRepository } from './product/CreateItemUseCase';
import type { IOrderRepository } from './order/CreateItemUseCase';

export interface ContainerRegistry {
  'IUserRepository': IUserRepository;
  'IProductRepository': IProductRepository;
  'IOrderRepository': IOrderRepository;
}
