/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 *
 * Module: CoreModule
 */
import { ContainerModule, Lifecycle } from '@notjustcoders/di-container';
import { PriorityReviewSessionBuilderService, Sm2SpacedRepetitionService, sm2StateStore } from '../../infra/services/ReviewServices';
import { GetStatisticsUseCase } from '../../application/statistics/GetStatisticsUseCase';
import { AsyncStorageNotificationPreferencesRepository, ExpoLocalNotificationScheduler, NotificationContentBuilder, NotificationDecisionService, ScheduleDailyReviewReminderUseCase, createOnReviewSessionEndedDailyReminder } from '../../application/notifications/NotificationEntities';
import { createAddWordUseCase, createCreateSourceUseCase, createDeleteSourceUseCase, createDeleteWordUseCase, createGetAllSourcesUseCase, createGetAllWordsUseCase, createGetWordUseCase, createSearchWordsUseCase, createSourceRepository, createUpdateSourceUseCase, createUpdateWordUseCase, createWordEntryRepository } from '../../infra/persistence/vocabulary/VocabularyFactories';
import { eventBus, uuidGenerator } from '../../infra/shared/shared';

export const coreModule = new ContainerModule()
  .register('SpacedRepetitionService', { useClass: Sm2SpacedRepetitionService, lifecycle: Lifecycle.Singleton })
  .register('ReviewSessionBuilderService', { useClass: PriorityReviewSessionBuilderService, lifecycle: Lifecycle.Singleton })
  .register(GetStatisticsUseCase, { useClass: GetStatisticsUseCase, dependencies: ['IWordEntryRepository', IReviewSessionRepository], lifecycle: Lifecycle.Singleton })
  .register('INotificationDecisionService', { useClass: NotificationDecisionService, dependencies: ['IUserNotificationPreferencesRepository'], lifecycle: Lifecycle.Singleton })
  .register('INotificationContentBuilder', { useClass: NotificationContentBuilder, lifecycle: Lifecycle.Singleton })
  .register('ILocalNotificationScheduler', { useClass: ExpoLocalNotificationScheduler, lifecycle: Lifecycle.Singleton })
  .register('IUserNotificationPreferencesRepository', { useClass: AsyncStorageNotificationPreferencesRepository, lifecycle: Lifecycle.Singleton })
  .register(ScheduleDailyReviewReminderUseCase, { useClass: ScheduleDailyReviewReminderUseCase, dependencies: ['INotificationDecisionService', 'IUserNotificationPreferencesRepository', GetStatisticsUseCase, 'INotificationContentBuilder', 'ILocalNotificationScheduler'], lifecycle: Lifecycle.Singleton })
  .register('createOnReviewSessionEndedDailyReminder', { useFactory: createOnReviewSessionEndedDailyReminder, dependencies: [ScheduleDailyReviewReminderUseCase], lifecycle: Lifecycle.Singleton })
  .register('IWordEntryRepository', { useFactory: createWordEntryRepository, lifecycle: Lifecycle.Transient })
  .register('ISourceRepository', { useFactory: createSourceRepository, lifecycle: Lifecycle.Transient })
  .register('createAddWordUseCase', { useFactory: createAddWordUseCase, dependencies: ['IWordEntryRepository', 'IEventBus', 'IUuidGenerator'], lifecycle: Lifecycle.Singleton })
  .register('createGetWordUseCase', { useFactory: createGetWordUseCase, dependencies: ['IWordEntryRepository'], lifecycle: Lifecycle.Singleton })
  .register('createSearchWordsUseCase', { useFactory: createSearchWordsUseCase, dependencies: ['IWordEntryRepository'], lifecycle: Lifecycle.Singleton })
  .register('createUpdateWordUseCase', { useFactory: createUpdateWordUseCase, dependencies: ['IWordEntryRepository'], lifecycle: Lifecycle.Singleton })
  .register('createGetAllWordsUseCase', { useFactory: createGetAllWordsUseCase, dependencies: ['IWordEntryRepository'], lifecycle: Lifecycle.Singleton })
  .register('createDeleteWordUseCase', { useFactory: createDeleteWordUseCase, dependencies: ['IWordEntryRepository'], lifecycle: Lifecycle.Singleton })
  .register('createCreateSourceUseCase', { useFactory: createCreateSourceUseCase, dependencies: ['ISourceRepository', 'IUuidGenerator'], lifecycle: Lifecycle.Singleton })
  .register('createGetAllSourcesUseCase', { useFactory: createGetAllSourcesUseCase, dependencies: ['ISourceRepository'], lifecycle: Lifecycle.Singleton })
  .register('createUpdateSourceUseCase', { useFactory: createUpdateSourceUseCase, dependencies: ['ISourceRepository'], lifecycle: Lifecycle.Singleton })
  .register('createDeleteSourceUseCase', { useFactory: createDeleteSourceUseCase, dependencies: ['ISourceRepository'], lifecycle: Lifecycle.Singleton })
  .register('IEventBus', { useValue: eventBus, lifecycle: Lifecycle.Singleton })
  .register('IUuidGenerator', { useValue: uuidGenerator, lifecycle: Lifecycle.Singleton })
  .register('sm2StateStore', { useValue: sm2StateStore, lifecycle: Lifecycle.Singleton });
