/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 *
 * Module: NotificationModule
 */
import { ContainerModule, Lifecycle } from '@notjustcoders/di-container';
import { AsyncStorageNotificationPreferencesRepository, ExpoLocalNotificationScheduler, NotificationContentBuilder, NotificationDecisionService, createOnReviewSessionEndedDailyReminder, createScheduleDailyReviewReminderUseCase } from '../../application/notifications/NotificationEntities';
import { GetStatisticsUseCase } from '../../application/statistics/GetStatisticsUseCase';

export const notificationModule = new ContainerModule()
  .register('INotificationDecisionService', { useClass: NotificationDecisionService, dependencies: ['IUserNotificationPreferencesRepository'], lifecycle: Lifecycle.Singleton })
  .register('INotificationContentBuilder', { useClass: NotificationContentBuilder, lifecycle: Lifecycle.Singleton })
  .register('ILocalNotificationScheduler', { useClass: ExpoLocalNotificationScheduler, lifecycle: Lifecycle.Singleton })
  .register('IUserNotificationPreferencesRepository', { useClass: AsyncStorageNotificationPreferencesRepository, lifecycle: Lifecycle.Singleton })
  .register('ScheduleDailyReviewReminderUseCase', { useFactory: createScheduleDailyReviewReminderUseCase, dependencies: ['INotificationDecisionService', 'IUserNotificationPreferencesRepository', GetStatisticsUseCase, 'INotificationContentBuilder', 'ILocalNotificationScheduler'], lifecycle: Lifecycle.Transient })
  .register('createOnReviewSessionEndedDailyReminder', { useFactory: createOnReviewSessionEndedDailyReminder, dependencies: ['ScheduleDailyReviewReminderUseCase'], lifecycle: Lifecycle.Singleton });
