/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 *
 * Module: ReviewModule
 */
import { ContainerModule, Lifecycle } from '@notjustcoders/di-container';
import { PriorityReviewSessionBuilderService, Sm2SpacedRepetitionService, createEndReviewSessionUseCase, createOnReviewSessionEnded, createRecordAnswerUseCase, createReviewSessionRepository, createStartReviewSessionUseCase, sm2StateStore } from '../../infra/services/ReviewServices';

export const reviewModule = new ContainerModule()
  .register('SpacedRepetitionService', { useClass: Sm2SpacedRepetitionService, lifecycle: Lifecycle.Singleton })
  .register('ReviewSessionBuilderService', { useClass: PriorityReviewSessionBuilderService, lifecycle: Lifecycle.Singleton })
  .register('IReviewSessionRepository', { useFactory: createReviewSessionRepository, lifecycle: Lifecycle.Transient })
  .register('createStartReviewSessionUseCase', { useFactory: createStartReviewSessionUseCase, dependencies: ['IWordEntryRepository', 'IReviewSessionRepository', 'ReviewSessionBuilderService', 'IUuidGenerator'], lifecycle: Lifecycle.Singleton })
  .register('createRecordAnswerUseCase', { useFactory: createRecordAnswerUseCase, dependencies: ['IReviewSessionRepository', 'IEventBus'], lifecycle: Lifecycle.Singleton })
  .register('createEndReviewSessionUseCase', { useFactory: createEndReviewSessionUseCase, dependencies: ['IReviewSessionRepository', 'IEventBus'], lifecycle: Lifecycle.Singleton })
  .register('createOnReviewSessionEnded', { useFactory: createOnReviewSessionEnded, dependencies: ['IWordEntryRepository', 'SpacedRepetitionService'], lifecycle: Lifecycle.Singleton })
  .register('sm2StateStore', { useValue: sm2StateStore, lifecycle: Lifecycle.Singleton });
