/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 *
 * Module: SharedModule
 */
import { ContainerModule, Lifecycle } from '@notjustcoders/di-container';
import { eventBus, uuidGenerator } from '../../infra/shared/shared';

export const sharedModule = new ContainerModule()
  .register('IEventBus', { useValue: eventBus, lifecycle: Lifecycle.Singleton })
  .register('IUuidGenerator', { useValue: uuidGenerator, lifecycle: Lifecycle.Singleton });
