/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 *
 * Module: StatisticsModule
 */
import { ContainerModule, Lifecycle } from '@notjustcoders/di-container';
import { GetStatisticsUseCase } from '../../application/statistics/GetStatisticsUseCase';

export const statisticsModule = new ContainerModule()
  .register(GetStatisticsUseCase, { useClass: GetStatisticsUseCase, dependencies: ['IWordEntryRepository', 'IReviewSessionRepository'], lifecycle: Lifecycle.Singleton });
