/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 *
 * Module: VocabularyModule
 */
import { ContainerModule, Lifecycle } from '@notjustcoders/di-container';
import { createAddWordUseCase, createCreateSourceUseCase, createDeleteSourceUseCase, createDeleteWordUseCase, createGetAllSourcesUseCase, createGetAllWordsUseCase, createGetWordUseCase, createSearchWordsUseCase, createSourceRepository, createUpdateSourceUseCase, createUpdateWordUseCase, createWordEntryRepository } from '../../infra/persistence/vocabulary/VocabularyFactories';

export const vocabularyModule = new ContainerModule()
  .register('IWordEntryRepository', { useFactory: createWordEntryRepository, lifecycle: Lifecycle.Transient })
  .register('ISourceRepository', { useFactory: createSourceRepository, lifecycle: Lifecycle.Transient })
  .register('createAddWordUseCase', { useFactory: createAddWordUseCase, dependencies: ['IWordEntryRepository', 'IEventBus', 'IUuidGenerator'], lifecycle: Lifecycle.Singleton })
  .register('createGetWordUseCase', { useFactory: createGetWordUseCase, dependencies: ['IWordEntryRepository'], lifecycle: Lifecycle.Singleton })
  .register('createSearchWordsUseCase', { useFactory: createSearchWordsUseCase, dependencies: ['IWordEntryRepository'], lifecycle: Lifecycle.Singleton })
  .register('createUpdateWordUseCase', { useFactory: createUpdateWordUseCase, dependencies: ['IWordEntryRepository'], lifecycle: Lifecycle.Singleton })
  .register('createGetAllWordsUseCase', { useFactory: createGetAllWordsUseCase, dependencies: ['IWordEntryRepository'], lifecycle: Lifecycle.Singleton })
  .register('createDeleteWordUseCase', { useFactory: createDeleteWordUseCase, dependencies: ['IWordEntryRepository'], lifecycle: Lifecycle.Singleton })
  .register('createCreateSourceUseCase', { useFactory: createCreateSourceUseCase, dependencies: ['ISourceRepository', 'IUuidGenerator'], lifecycle: Lifecycle.Singleton })
  .register('createGetAllSourcesUseCase', { useFactory: createGetAllSourcesUseCase, dependencies: ['ISourceRepository'], lifecycle: Lifecycle.Singleton })
  .register('createUpdateSourceUseCase', { useFactory: createUpdateSourceUseCase, dependencies: ['ISourceRepository'], lifecycle: Lifecycle.Singleton })
  .register('createDeleteSourceUseCase', { useFactory: createDeleteSourceUseCase, dependencies: ['ISourceRepository'], lifecycle: Lifecycle.Singleton });
