/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 * 
 * This file provides type-safe resolution for string-based tokens.
 */
import type { IUserRepository } from './user/IUserRepository';
import type { ITodoRepository } from './todo/ITodoRepository';
import { createFindUserUseCase } from './user/factories/createFindUserUseCase';
import { createAddTodoUseCase } from './todo/factories/createAddTodoUseCase';

export interface ContainerRegistry {
  'IUserRepository': IUserRepository;
  'ITodoRepository': ITodoRepository;
  'createFindUserUseCase': ReturnType<typeof createFindUserUseCase>;
  'createAddTodoUseCase': ReturnType<typeof createAddTodoUseCase>;
}
