/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 * 
 * Module: TodoModule
 */
import { ContainerModule, Lifecycle } from '@notjustcoders/di-container';
import { TodoService } from '../todo/TodoService';
import { TodoRepository } from '../todo/TodoRepository';
import { Todo } from '../todo/Todo';

export const todoModule = new ContainerModule()
  .register('ITodoService', { useClass: TodoService, dependencies: ['ITodoRepository', 'IUserRepository'], lifecycle: Lifecycle.Singleton })
  .register('ITodoRepository', { useClass: TodoRepository, lifecycle: Lifecycle.Singleton })
  .register(Todo, { useClass: Todo, lifecycle: Lifecycle.Singleton });
