/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 * 
 * Module: UserModule
 */
import { ContainerModule, Lifecycle } from '@notjustcoders/di-container';
import { UserService } from '../user/UserService';
import { UserRepository } from '../user/UserRepository';
import { User } from '../user/User';

export const userModule = new ContainerModule()
  .register('IUserService', { useClass: UserService, dependencies: ['IUserRepository'], lifecycle: Lifecycle.Singleton })
  .register('IUserRepository', { useClass: UserRepository, lifecycle: Lifecycle.Singleton })
  .register(User, { useClass: User, lifecycle: Lifecycle.Singleton });
