/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 * 
 * This file provides type-safe resolution for string-based tokens.
 */
import type { IUserRepository } from './repositories/IUserRepository';
import type { ITodoRepository } from './repositories/ITodoRepository';
import { createTodoUseCase } from './factories/todoUseCaseFactory';

export interface ContainerRegistry {
  'IUserRepository': IUserRepository;
  'ITodoRepository': ITodoRepository;
  'createTodoUseCase': ReturnType<typeof createTodoUseCase>;
}
