/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 * 
 * This file provides type-safe resolution for string-based tokens.
 */
import type { IProductRepository } from '../repositories/IProductRepository';
import type { IProductService } from '../services/IProductService';

export interface ContainerRegistry {
  'IProductRepository': IProductRepository;
  'IProductService': IProductService;
}
