/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 */
import { Container, Lifecycle } from '@notjustcoders/di-container';
import type { ContainerRegistry } from './container.gen.d';
import { ProductService } from '../services/ProductService';
import { InMemoryProductRepository } from '../repositories/InMemoryProductRepository';

export const container = new Container<ContainerRegistry>();

container.register('IProductService', {
  useClass: ProductService,
  dependencies: ['IProductRepository'],
  lifecycle: Lifecycle.Singleton,
});

container.register('IProductRepository', {
  useClass: InMemoryProductRepository,
  lifecycle: Lifecycle.Singleton,
});
