/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 * 
 * Module: ProductModule
 */
import { ContainerModule, Lifecycle } from 'ioc-arise';
import { ProductUseCase } from '../use-cases/ProductUseCase';
import { InternalProductNestedUseCase } from '../use-cases/InternalProductNestedUseCase';
import { ProductRepository } from '../implementations/ProductRepository';

export const productModule = new ContainerModule()
  .register(ProductUseCase, { useClass: ProductUseCase, dependencies: ['AbstractProductRepository', 'AbstractUserRepository', InternalProductNestedUseCase], lifecycle: Lifecycle.Singleton })
  .register(InternalProductNestedUseCase, { useClass: InternalProductNestedUseCase, dependencies: ['AbstractProductRepository'], lifecycle: Lifecycle.Singleton })
  .register('AbstractProductRepository', { useClass: ProductRepository, lifecycle: Lifecycle.Singleton });
